spring:
  data:
    mongodb:
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
  application:
    name: category-service
  zipkin:
    base-url: http://localhost:9411/  
    locator:
      discovery:
        enable: true
server:
  port: 9400
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka