server:
  port: 8080
  
spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
      - id: user-api
        uri: http://localhost:8088/
        predicates:
        - Path=/api/ads/** 
      - id: authentication-api
        uri: http://localhost:8086/
        predicates: 
        - Path=/login
      - id: awareness-api
        uri: http://localhost:8084/
        predicates:
        - Path=/api/awareness/**
      - id: natwestdb-api
        uri: http://localhost:8087/
        predicates:
        - Path=api/natwestdb/get
      - id: login-api
        uri: http://localhost:8089/**
        predicates:
        - Path=api/natwestdb/get          

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
